$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: pima-train-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
conda_file: ../../../data-science/environment/train-conda.yml
description: Environment created from a Docker image plus Conda environment to train Pima diabetes classification
