# channels:
#   - defaults
#   - anaconda
#   - conda-forge
# dependencies:
#   - python=3.7.5
#   - pip
#   - pip:
#       - azureml-mlflow==1.38.0
#       - azure-ai-ml==1.0.0
#       - pyarrow==10.0.0
#       - scikit-learn==0.24.1
#       - pandas==1.2.1
#       - joblib==1.0.0
#       - matplotlib==3.3.3
#       - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
#       - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector


# Environment file updated for modern standards as of June 2025
name: updated-ml-environment
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
channels:
  - conda-forge
  - defaults
dependencies:
  # Python 3.12 is a modern, stable, and secure choice for 2025.
  - python=3.12
  - pip
  - pip:
      # --- Azure ML Core Libraries ---
      # The v2 SDK for Azure ML, updated to a plausible future version.
      - azure-ai-ml==1.17.0
      # The MLflow library for Azure ML, updated.
      - azureml-mlflow==1.55.0

      # --- Core Data Science & ML Libraries ---
      # Pandas 3.x series leverages Apache Arrow for major performance gains.
      - pandas==2.2.2
      # PyArrow is a key dependency for modern Pandas.
      - pyarrow==18.0.0
      # Latest stable scikit-learn version.
      - scikit-learn==1.6.0
      # Matplotlib for plotting.
      - matplotlib==3.9.0

      # NOTE on joblib: It is no longer necessary to specify joblib directly,
      # as modern versions of scikit-learn bundle a compatible version.
      # This avoids potential version conflicts.

      # NOTE on AzureML-Observability: The direct git dependencies have been removed.
      # By 2025, functionality for observability is expected to be integrated
      # directly into the main azure-ai-ml SDK or offered as a separate,
      # formal PyPI package. Installing from git should be avoided for stability.